### ISSUE TITLE
Support for Xprinter printers

### ISSUE THREAD

**Issue by breezycloud** [NielsLeenheer/WebUSBReceiptPrinter#1]
Hi, i found this library to very interesting can you please add support for Xprinters?

**Comment by NielsLeenheer** [comment]
I don't have any Xprinter printer in my lab right now. Got one incoming, once it arrives I'll see what I can do.

**Comment by NielsLeenheer** [comment]
Quicker than I expected, two Xprinter printers arrived today - straight from the factory in China: 

- XP-T80Q
- XP-N160II

It was pretty easy to add support for both of them - they look different, but the internals are pretty similar. They run the same type of firmware, but different versions. So they work really similar, but not completely identical. They actually use different USB endpoints, but it was really easy to work around that by automatically detecting the right endpoint.

I'll release an update soon. Because the codepage mapping is different from all other printers so far, I do need to update ThermalPrinterEncoder and EscPosEncoder too.

**Comment by NielsLeenheer** [comment]
WebUSBReceiptPrinter, ThermalPrinterEncoder and EscPosEncoder have been updated and available on NPM.
